# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentfiles < Formula
  desc "A CLI for managing AI agent configuration files"
  homepage "https://github.com/devbydaniel/agentfiles"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/agentfiles/releases/download/v0.6.0/agentfiles_0.6.0_darwin_amd64.tar.gz"
      sha256 "84c1d31979a608ec10d7498a55afe85094345261a14b6fff6902dc4d126634be"

      define_method(:install) do
        bin.install "af"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/agentfiles/releases/download/v0.6.0/agentfiles_0.6.0_darwin_arm64.tar.gz"
      sha256 "f12f39720fbc4971944541001264c394a29e5ea7d29ee4ea58c084c7b99e36f1"

      define_method(:install) do
        bin.install "af"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/agentfiles/releases/download/v0.6.0/agentfiles_0.6.0_linux_amd64.tar.gz"
      sha256 "9c851ab05626cff2ae9b4b78fe7d3db95b741829cac6b0d4346091848ec3934e"
      define_method(:install) do
        bin.install "af"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/agentfiles/releases/download/v0.6.0/agentfiles_0.6.0_linux_arm64.tar.gz"
      sha256 "479a688c785cc11ff857e8767cb79b1c4fa2c18d7fe40913aa9137b06e6ad9d8"
      define_method(:install) do
        bin.install "af"
      end
    end
  end
end
