# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Browser automation CLI for AI agents"
  homepage "https://github.com/devbydaniel/bb"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/bb/releases/download/v1.0.1/bb_1.0.1_darwin_amd64.tar.gz"
      sha256 "0cb4be4f982cd4f5ce634b4c72f2205420145e29784d753b7a7bec24d82e2acb"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/bb/releases/download/v1.0.1/bb_1.0.1_darwin_arm64.tar.gz"
      sha256 "618f0b0b98fed997d4815e3e65ef31ef7a507c0d6b5b16dfc496cb15addd6b75"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/bb/releases/download/v1.0.1/bb_1.0.1_linux_amd64.tar.gz"
      sha256 "7cc5efa2001ffa8c0389a262d320019d0178a231002299e920e649918bcd62f5"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/bb/releases/download/v1.0.1/bb_1.0.1_linux_arm64.tar.gz"
      sha256 "6d2a39fd9b04f1e34fdd6d89fc2f3fdad8dfeb6e5331f0bc23a685d38f5931fa"
      def install
        bin.install "bb"
      end
    end
  end
end
