# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notion < Formula
  desc "A CLI for accessing Notion content"
  homepage "https://github.com/devbydaniel/notioncli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/notioncli/releases/download/v0.1.1/notion_0.1.1_darwin_amd64.tar.gz"
      sha256 "7336a659fa46dd81894bac6cbccf1329e6ba34d825b20f21144298e98830f3aa"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/notioncli/releases/download/v0.1.1/notion_0.1.1_darwin_arm64.tar.gz"
      sha256 "efdf8ad6564e735f818b60e5c1bf7668200bc8e298b726c662778aef49131070"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/notioncli/releases/download/v0.1.1/notion_0.1.1_linux_amd64.tar.gz"
      sha256 "0d234d7141f47d9a34cfee732b687232d32e2601f6f7f127efb4f20b9e6b684c"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/notioncli/releases/download/v0.1.1/notion_0.1.1_linux_arm64.tar.gz"
      sha256 "49951159fb225e69e280192faba4540ec0c0e6b72355c908e825b808d3c3a321"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end
end
