# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtSync < Formula
  desc "Sync server for tt task manager"
  homepage "https://github.com/devbydaniel/tt"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt-sync_0.4.1_darwin_amd64.tar.gz"
      sha256 "43e16d3cee7901e352e632af822295c5d7b4eb2ff04d535e044d2c63ff714c3a"

      def install
        bin.install "tt-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt-sync_0.4.1_darwin_arm64.tar.gz"
      sha256 "32bb3775628c88fc5db4d69efc32ada8b1ad60bb76b63f5547be9a5a7b7c2ac4"

      def install
        bin.install "tt-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt-sync_0.4.1_linux_amd64.tar.gz"
      sha256 "b56997e299fcb5b885d24b34ac0afc5fbb8e68697901c3907c065cb2c4e38c80"
      def install
        bin.install "tt-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt-sync_0.4.1_linux_arm64.tar.gz"
      sha256 "1eb7ba8ad5bdb2547b6ff8d5601878ffbc36bed75dcf9582d081b32cf22aa569"
      def install
        bin.install "tt-sync"
      end
    end
  end
end
