# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtSync < Formula
  desc "Sync server for tt task manager"
  homepage "https://github.com/devbydaniel/tt"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/tt/releases/download/v0.2.0/tt-sync_0.2.0_darwin_amd64.tar.gz"
      sha256 "1fe35c8336411159681630e33db5ce6c492dc04ca43eab3d96e443687c7ddf45"

      def install
        bin.install "tt-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/tt/releases/download/v0.2.0/tt-sync_0.2.0_darwin_arm64.tar.gz"
      sha256 "c805e9a9b0de1b194b03b40f7153b9f5e670903e401d51b7cf4555030e883595"

      def install
        bin.install "tt-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.2.0/tt-sync_0.2.0_linux_amd64.tar.gz"
      sha256 "9e11039635341fe1a266b96dec55fe18426f7d3972e226d2a6ae5f3fd33a1e23"
      def install
        bin.install "tt-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.2.0/tt-sync_0.2.0_linux_arm64.tar.gz"
      sha256 "46a45a66184445982d35d86a43e1c48a97e7ec6c7ff50ceddb661359d3b74d0f"
      def install
        bin.install "tt-sync"
      end
    end
  end
end
