# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc "A CLI & TUI task manager"
  homepage "https://github.com/devbydaniel/tt"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt_0.4.1_darwin_amd64.tar.gz"
      sha256 "caa88718ecc07006644daed989cb25374255683a592975da997b0620c3b6f273"

      def install
        bin.install "tt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt_0.4.1_darwin_arm64.tar.gz"
      sha256 "2f676c9d1ca4b9723b461a61e07efb72c514e8f481697c4ca85618beae11d5b0"

      def install
        bin.install "tt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt_0.4.1_linux_amd64.tar.gz"
      sha256 "066930b4f0065d3112f7835b7a6f154cf8b6b3c909da532186d5441e5965a631"
      def install
        bin.install "tt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.1/tt_0.4.1_linux_arm64.tar.gz"
      sha256 "6247fe1fd9d74232ce8616038e7a8d3b72c6b7bd0cf823e3c36bf42f8adaca79"
      def install
        bin.install "tt"
      end
    end
  end
end
