# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc "A CLI & TUI task manager"
  homepage "https://github.com/devbydaniel/tt"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.2/tt_0.4.2_darwin_amd64.tar.gz"
      sha256 "20fb9f859c397c83e1484f55d3ea54aea4f66d4a43dc57c0db058266c0136f58"

      define_method(:install) do
        bin.install "tt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.2/tt_0.4.2_darwin_arm64.tar.gz"
      sha256 "36877148c0e58b54c62713a54e8cb68b1243dcb0f29668ba3227c91b702a64d0"

      define_method(:install) do
        bin.install "tt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.2/tt_0.4.2_linux_amd64.tar.gz"
      sha256 "30962e9e7086964477ec97eccd2107fcd5fb2eadbed43d9ac5fed6c53bd86887"
      define_method(:install) do
        bin.install "tt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbydaniel/tt/releases/download/v0.4.2/tt_0.4.2_linux_arm64.tar.gz"
      sha256 "e6c8e98c8e1d5fac79fefde3a537fbb1b9e8fb01e7c2793e9edac451845de105"
      define_method(:install) do
        bin.install "tt"
      end
    end
  end
end
